In [3]:
import numpy as np

In [4]:
a = np.array([[1,2,3,4,5]])

In [5]:
print(a)
print(a.shape)

[[1 2 3 4 5]]
(1, 5)


In [6]:
print(a.shape)

(1, 5)


In [7]:
print(a.shape)

(1, 5)


In [3]:
np.ones((4, 2, 2), dtype="int32")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [5]:
np.full((2,4),3)

array([[3, 3, 3, 3],
       [3, 3, 3, 3]])

In [8]:
np.random.rand(3,4)

array([[0.03931347, 0.53795709, 0.92318878, 0.62615868],
       [0.59232105, 0.46657362, 0.88566138, 0.61748933],
       [0.75558408, 0.90801283, 0.56823256, 0.2991943 ]])

In [100]:
np.random.randint(1,10, size=(4,3))

array([[9, 8, 5],
       [2, 9, 2],
       [5, 6, 9],
       [4, 5, 3]])

In [101]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [106]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [112]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1, 1:-1]=z
print(output)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Be careful when copying arrays!!

In [116]:
a = np.array([1, 2, 3])
b = a.copy()
b[0]=100
print(a)
print(b)

[1 2 3]
[100   2   3]


#### Liner Algebra

In [130]:
a = np.full((2,3),2)
print(a)

b = np.ones((3,2))
print(b)

np.matmul(a,b)


[[2 2 2]
 [2 2 2]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


array([[6., 6.],
       [6., 6.]])

In [133]:
c = np.identity(3)
print(c)
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

#### statistics

In [135]:
stats = np.array([[1,2,3],[4,5,6]])

In [136]:
np.min(stats)

1

In [141]:
np.max(stats, axis=1)

array([3, 6])

In [149]:
# 行方向がaxis=0
np.sum(stats, axis=0)

array([5, 7, 9])

In [150]:
# 列方向がaxis=1
np.sum(stats, axis=1)

array([ 6, 15])

In [151]:
# 
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [153]:
c = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [157]:
print(c[2:4, 0:2])

[[11 12]
 [16 17]]


In [166]:
print(c[[0,1,2,3],[1,2,3,4]])

[ 2  8 14 20]


In [176]:
print(c[[0,4,5],3:])

[[ 4  5]
 [24 25]
 [29 30]]
